Repository CouncilDataProject/seattle, pull requests merged in 2020-02, with the labels that each got.

#70 feature/add-close-button-to mini-player (#61)
  src/components/Event.jsx
Labels: enhancement

#71 feature/add-error-handling
  src/App.js
  src/api/database.js
  src/api/eventApi.js
  src/api/index.js
  src/api/personApi.js
  src/components/Event.jsx
  src/components/EventsFilter.jsx
  src/components/GeneralErrorBoundary.jsx
  src/containers/AllEvents.jsx
  src/containers/DataApiContainer.jsx
  src/containers/Event.jsx
  src/containers/EventCardGroup.jsx
  src/containers/EventsFilterContainer.jsx
  src/containers/PeopleCardGroupContainer.jsx
  src/containers/PersonContainer.jsx
  src/hooks/useDataApi.js
  src/pages/AllEvents.jsx
  src/pages/Event.jsx
  src/pages/Home.jsx
  src/pages/People.jsx
  src/pages/Person.jsx
  src/pages/Search.jsx
Labels: bug, enhancement

#72 admin/update-bug-template
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: documentation
